### ISSUE TITLE
Package missing?

### ISSUE THREAD

**Issue by benlobach** [infoservio/donate-fast#1]
It doesn't look like Donate Fast is available inside our Craft installation, and composer throws an error that the package doesn't exist when attempting to require the plugin manually. Do you have a recommendation for installing this plugin through composer or Craft? Thanks!

**Comment by geojensen** [comment]
Hi Ben,

Remind me early Monday morning.  I'll look into it.  ~GJ

**Comment by benlobach** [comment]
Sure thing!

**Comment by benlobach** [comment]
GJ, would you mind looking into this for us?

**Comment by benlobach** [comment]
GJ, just wondering if you've had a chance to look into this problem?

**Comment by geojensen** [comment]
Thanks for the reminder. Let me look into this for the next few minutes.
~GJ

**Comment by geojensen** [comment]
Can you Zoom? https://zoom.us/j/3178746971 . ~GJ

**Comment by benlobach** [comment]
Thanks, GJ!

**Comment by geojensen** [comment]
Ben,
I can give you write access to the composer file for further edits.

Vlad said: *...because stripe have new major version it probably wouldn't
work.. but you can open this plugin for editing for Ben if he want to
update it... *
